# silver_config/silver_warehouse_task.py

from pyspark.sql.types import StructType, StructField, StringType, BooleanType, IntegerType, DoubleType, ArrayType, DecimalType
from silver.common import make_raw_path, DELTA_BASE, REJECT_BASE, LOGGING_BASE, MARKER_BASE

WAREHOUSE_TASK_CONFIG = {
    "job_name": "warehouse_task",
    "raw_path": make_raw_path("warehouse_task"),
    "delta_path": f"{DELTA_BASE}/warehouse_task",
    "reject_path": f"{REJECT_BASE}/warehouse_task",
    "log_path": f"{LOGGING_BASE}/warehouse_task",
    "marker_path": f"{MARKER_BASE}/warehouse_task",
    "use_file_marker": True,
    "key_columns": ["EWMWarehouse", "WarehouseTask"],
    "required_columns": ["EWMWarehouse", "WarehouseTask"],
    "partition_by": ["WhseTaskCrtnUTCDateTime"],  # hoặc bạn có thể dùng record_date nếu không chắc chắn field này luôn có
    "table_type": "fact",
    "flatten_expr": "explode(value) as record",
    "data_quality_rules": {
        "WhseTaskCrtnUTCDateTime": ["iso_date"],
        "WhseTaskLastChgUTCDateTime": ["iso_date"],
        "WhseTaskConfUTCDateTime": ["iso_date"],
        "WhseTaskPlannedClosingDateTime": ["iso_date"],
        "WhseTaskGoodsReceiptDateTime": ["iso_date"],
        "ShelfLifeExpirationDate": ["iso_date"]
    },
    "schema": StructType([
        StructField("value", ArrayType(StructType([
            StructField("EWMWarehouse", StringType()),
            StructField("WarehouseTask", StringType()),
            StructField("WarehouseTaskItem", StringType()),
            StructField("WarehouseOrder", StringType()),
            StructField("WhseTaskCrtnUTCDateTime", StringType()),
            StructField("WhseTaskLastChgUTCDateTime", StringType()),
            StructField("WhseTaskConfUTCDateTime", StringType()),
            StructField("ConfirmedByUser", StringType()),
            StructField("WhseTaskPlannedClosingDateTime", StringType()),
            StructField("WhseTaskGoodsReceiptDateTime", StringType()),
            StructField("WarehouseTaskStatus", StringType()),
            StructField("WarehouseProcessType", StringType()),
            StructField("WarehouseProcessCategory", StringType()),
            StructField("IsHandlingUnitWarehouseTask", BooleanType()),
            StructField("EWMHandlingUnitType", StringType()),
            StructField("HandlingUnitTypeGroup", StringType()),
            StructField("HomogeneousFullPalletPick", StringType()),
            StructField("EWMPutAwayPhysInvtryPlnSts", StringType()),
            StructField("EWMWhseTskLowStkChkPlnSts", StringType()),
            StructField("EWMPutAwayPhysInvtryExecSts", StringType()),
            StructField("EWMWhseTskLowStkChkExecSts", StringType()),
            StructField("Product", StringType()),
            StructField("Batch", StringType()),
            StructField("BatchChangeIsNotAllowed", BooleanType()),
            StructField("CountryOfOrigin", StringType()),
            StructField("ShelfLifeExpirationDate", StringType()),
            StructField("EWMStockType", StringType()),
            StructField("EWMStockUsage", StringType()),
            StructField("EWMStockOwner", StringType()),
            StructField("EntitledToDisposeParty", StringType()),
            StructField("WBSElementInternalID", StringType()),
            StructField("WBSElementExternalID", StringType()),
            StructField("SpecialStockIdfgSalesOrder", StringType()),
            StructField("SpecialStockIdfgSalesOrderItem", StringType()),
            StructField("ExecutingResource", StringType()),
            StructField("WarehouseMovementsReason", StringType()),
            StructField("ProductionOrder", StringType()),
            StructField("EWMProductionSupplyArea", StringType()),
            StructField("EWMDocumentCategory", StringType()),
            StructField("EWMReferenceDocumentCategory", StringType()),
            StructField("EWMDelivery", StringType()),
            StructField("EWMDeliveryItem", StringType()),
            StructField("PurchasingDocument", StringType()),
            StructField("PurchasingDocumentItem", StringType()),
            StructField("SalesDocument", StringType()),
            StructField("SalesDocumentItem", StringType()),
            StructField("BaseUnit", StringType()),
            StructField("EWMBaseUnitISOCode", StringType()),
            StructField("AlternativeUnit", StringType()),
            StructField("EWMAlternativeUnitISOCode", StringType()),
            StructField("TargetQuantityInBaseUnit", DecimalType(18, 3)),
            StructField("TargetQuantityInAltvUnit", DecimalType(18, 3)),
            StructField("ActualQuantityInBaseUnit", DecimalType(18, 3)),
            StructField("ActualQuantityInAltvUnit", DecimalType(18, 3)),
            StructField("DifferenceQuantityInBaseUnit", DecimalType(18, 3)),
            StructField("DifferenceQuantityInAltvUnit", DecimalType(18, 3)),
            StructField("WhseTaskNetWeightUnitOfMeasure", StringType()),
            StructField("WhseTaskNetWeight", DecimalType(15, 3)),
            StructField("WhseTaskNetVolumeUnitOfMeasure", StringType()),
            StructField("WhseTaskNetVolume", DecimalType(15, 3)),
            StructField("SourceStorageType", StringType()),
            StructField("SourceStorageSection", StringType()),
            StructField("SourceStorageBin", StringType()),
            StructField("SourceResource", StringType()),
            StructField("DestinationStorageType", StringType()),
            StructField("DestinationStorageSection", StringType()),
            StructField("DestinationStorageBin", StringType()),
            StructField("DestinationResource", StringType()),
            StructField("WhseTaskTwoStepPickingType", StringType()),
            StructField("WhseTaskTwoStepPickingRlvnce", StringType()),
            StructField("ActivityArea", StringType()),
            StructField("SourceHandlingUnit", StringType()),
            StructField("DestinationHandlingUnit", StringType()),
            StructField("WarehouseTaskExceptionCode", StringType()),
            StructField("WhseTaskSortingSequenceValue", DecimalType(10, 0)),
            StructField("WarehouseOrderSequenceValue", StringType()),
            StructField("WarehouseOrderActivityArea", StringType()),
            StructField("WarehouseOrderCreationRule", StringType()),
            StructField("WarehouseOrderQueue", StringType()),
            StructField("WarehouseActivityType", StringType()),
            StructField("EWMConsolidationGroup", StringType()),
            StructField("EWMWarehouseTaskPriority", IntegerType()),
            StructField("CreatedByUser", StringType()),
            StructField("EWMRoute", StringType()),
            StructField("EWMCanceledWarehouseTask", StringType()),
            StructField("SerialNumberRequiredLevel", StringType())
        ])))
    ]) 
}
