FROM postgres:14

# Copy cấu hình pg_hba.conf tạm vào thư mục init
COPY hive_pg_hba.conf /docker-entrypoint-initdb.d/hive_pg_hba.conf

# Copy init script (nếu cần thao tác gì thêm khi init)
COPY init-postgres.sh /docker-entrypoint-initdb.d/init-postgres.sh
RUN chmod +x /docker-entrypoint-initdb.d/init-postgres.sh
