{
 "title": "Airflow",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Scheduler Minitor",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airflow_scheduler_critical_section_duration_sum",
     "legendFormat": "Critical Section Duration"
    },
    {
     "expr": "airflow_scheduler_critical_section_query_duration_sum",
     "legendFormat": "Critical Section Query Duration"
    },
    {
     "expr": "airflow_scheduler_scheduler_loop_duration_sum",
     "legendFormat": "Loop Duration"
    }
   ]
  },
  {
   "title": "Executor",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "airflow_executor_open_slots", "legendFormat": "Executor Open Slots" },
    { "expr": "airflow_executor_queued_tasks", "legendFormat": "Executor Queue Tasks" },
    { "expr": "airflow_executor_running_tasks", "legendFormat": "Executor Running Task" }
   ]
  },
  {
   "title": "Path Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "airflow_dag_processing_file_path_queue_size",
     "legendFormat": "File Path Queue Size"
    },
    {
     "expr": "airflow_dag_processing_import_errors",
     "legendFormat": "Import Errors"
    }
   ]
  },
  {
   "title": "Number of Job Start and End",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 5 },
   "targets": [
    { "expr": "airflow_job_start", "legendFormat": "__auto" },
    { "expr": "airflow_job_end", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Dag Run",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 7 },
   "targets": [
    {
     "expr": "airflow_dagrun_dependency_check_sum",
     "legendFormat": "__auto"
    },
    { "expr": "airflow_dagrun_duration_failed", "legendFormat": "__auto" },
    {
     "expr": "airflow_dag_processing_last_duration_sum",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pool Monitor",
   "type": "state-timeline",
   "gridPos": { "h": 14, "w": 6, "x": 18, "y": 7 },
   "targets": [
    { "expr": "airflow_pool_open_slots", "legendFormat": "Open Slots" },
    { "expr": "airflow_pool_deferred_slots", "legendFormat": "Defferred_slots" },
    { "expr": "airflow_pool_queued_slots", "legendFormat": "Queue Slots" },
    { "expr": "airflow_pool_running_slots", "legendFormat": "Running Slots" },
    { "expr": "airflow_pool_starving_tasks", "legendFormat": "Starving Tasks" }
   ]
  },
  {
   "title": "Dag Processing",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "airflow_dag_processing_total_parse_time",
     "legendFormat": "__auto"
    },
    {
     "expr": "airflow_dag_processing_last_duration",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}