{
 "title": "Spark",
 "time": { "from": "2024-12-22T04:10:49.345Z", "to": "2024-12-22T04:32:04.345Z" },
 "panels": [
  {
   "title": "Pools Metaspace",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metrics_jvm_pools_Metaspace_usage_Value",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Minitor Workers",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "metrics_master_aliveWorkers_Number",
     "legendFormat": "Alive Worker"
    },
    { "expr": "metrics_master_workers_Number", "legendFormat": "Number Worker" },
    { "expr": "metrics_master_apps_Number", "legendFormat": "Number Apps" }
   ]
  },
  {
   "title": "JVM Heap Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "metrics_jvm_heap_usage_Value", "legendFormat": "__auto" }
   ]
  }
 ]
}